version: '3'
services:
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        ports: 
            - "8989:8989"
        volumes:
            - /home/root/configs/sonarr:/config
            - /mnt/tvshows:/tv
            - /mnt/downloads:/downloads
        environment:
            - TZ=ZA          
            - PGID=1000
            - PUID=1000
    plex:
        image: linuxserver/plex
        container_name: plex
        ports: 
            - "32400:32400"
        volumes:
            - /home/root/configs/plex:/config
            - /mnt/movies:/movies
        environment:
            - TZ=ZA          
            - PGID=1000
            - PUID=1000
    deluge:
        image: linuxserver/deluge
        container_name: deluge
        ports: 
            - "8112:8112"
        volumes:
            - /home/root/configs/deluge:/config
            - /mnt/downloads:/downloads
        environment:
            - TZ=ZA          
            - PGID=1000
            - PUID=1000
    #   plex:
    #     image: linuxserver/plex
    #     container_name: plex
    #     ports: 
    #         - "32400:32400"
    #     environment:
    #         - /etc/localtime:/etc/localtime:ro
    #         - PGID=1000
    #         - PUID=1000

      # radarr:
      #   image: linuxserver/radarr
      #   container_name: radarr
      #   ports: 7878:7878
      #   volumes:
      #       - /etc/localtime:/etc/localtime:ro
      #       - $HOME/.config/radarr:/config
      #   environment:
      #       - PGID=1000
      #       - PUID=1000

      # deluge:
      #   image: linuxserver/deluge
      #   container_name: deluge
      #   ports:
      
    #   plex:
    #     image: linuxserver/plex
    #     container_name: plex
    #     network_mode: "host"
    #     ports:
    #         - 32400:32400
    #     volumes:
    #         - /etc/localtime:/etc/localtime:ro
    #         - $HOME/.config/plexmediaserver:/config
    #         - /media/My Passport/peliculas:/data/movies
    #     restart: always
    #     environment:
    #         - VIRTUAL_PORT=32400
    #         - VIRTUAL_HOST=plex.htpc
    #         - VERSION=latest
    #         - PGID=1000
    #         - PUID=1000
    
    # jackett:
    #     image: linuxserver/jackett:90
    #     container_name: jackett
    #     restart: always
    #     ports:
    #         - 9117:9117
    #     environment:
    #         - VIRTUAL_HOST=jackett.htpc
    #         - PGID=1000
    #         - PUID=1000
    #     volumes:
    #         - $HOME/.config/jackett:/config
    #         - /etc/localtime:/etc/localtime:ro
    #         - $HOME/Downloads/torrents/completed/Movies:/downloads

    # dashboard:
    #     image: chimpchimp/manage-this-node
    #     container_name: dashboard
    #     restart: always
    #     network_mode: "bridge"
    #     ports:
    #         - 3000:3000
    #     environment:
    #         - VIRTUAL_HOST=dashboard.htpc
    #         - PGID=1000
    #         - PUID=1000
    #     volumes:
    #         - $HOME/.config/dashboard:/config
    #         - /etc/localtime:/etc/localtime:ro
    #         - $HOME/Downloads/torrents/completed/Movies:/downloads

    # portainer:
    #     image: portainer/portainer
    #     container_name: portainer
    #     restart: always
    #     network_mode: "bridge"
    #     ports:
    #         - "9000:9000"
    #     volumes:
    #         - /home/ina/.config/portainer:/data:rw
    #         - /var/run/docker.sock:/tmp/docker.sock:ro
    #         - /etc/localtime:/etc/localtime:ro

    # nginx-proxy:
    #     image: jwilder/nginx-proxy
    #     container_name: nginx-proxy
    #     ports:
    #         - "80:80"
    #     volumes:
    #         - /var/run/docker.sock:/tmp/docker.sock:ro

    # emby:
    #     image: emby/embyserver
    #     container_name: emby
    #     # net: host
    #     ports:
    #         - 8096:8096
    #     volumes:
    #         - /etc/localtime:/etc/localtime:ro
    #         - $HOME/.config/embyserver:/config
    #         - /media/My Passport/peliculas:/media
    #     environment:
    #         - VIRTUAL_PORT=8096
    #         - VIRTUAL_HOST=emby.htpc
    #         - AUTO_UPDATES_ON=true
    #         - APP_UID=1000
    #         - APP_GID=1000

    # ubot:
    #     image: inakiabt/utorrent-bot
    #     container_name: ubot
    #     restart: always
    #     links:
    #         - utorrent
    #     env_file: $HOME/.config/ubot/env

    # mrpotato:
    #     image: rolfkoenders/potato
    #     container_name: mrpotato
    #     restart: always
    #     links:
    #         - couchpotato
    #     env_file: $HOME/.config/mrpotato/env

    # dashboard:
    #     image: chimpchimp/manage-this-node
    #     container_name: dashboard
    #     ports:
    #         - 3000:3000
    #     volumes:
    #         - $HOME/.config/dashboard:/config
    #     restart: always
    #     environment:
    #         - VIRTUAL_HOST=dashboard.htpc
    #         - PGID=1000
    #         - PUID=1000

    # couchpotato:
    #     image: linuxserver/couchpotato
    #     container_name: couchpotato
    #     # network_mode: "host"
    #     volumes:
    #         - /etc/localtime:/etc/localtime:ro
    #         - $HOME/.config/couchpotato:/config
    #         - $HOME/Downloads/torrents/completed/Movies:/downloads
    #         - /media/My Passport/peliculas:/movies
    #     ports:
    #         - 5050:5050
    #     links:
    #         - jackett
    #         - plex
    #         - utorrent
    #     restart: always
    #     environment:
    #         - VIRTUAL_HOST=couchpotato.htpc
    #         - PGID=1000
    #         - PUID=1000

    # utorrent:
    #     image: ekho/utorrent
    #     container_name: utorrent
    #     # network_mode: "host"
    #     volumes:
    #         - /etc/localtime:/etc/localtime:ro
    #         - $HOME/Downloads:/data
    #         - $HOME/.config/utorrent:/utorrent
    #     ports:
    #         - 8080:8080
    #         - 6881:6881
    #     restart: always
    #     environment:
    #         - VIRTUAL_PORT=8080
    #         - VIRTUAL_HOST=utorrent.htpc

    # hamachi:
    #     image: gfjardim/hamachi
    #     container_name: hamachi
    #     network_mode: "host"
    #     volumes:
    #         - /etc/localtime:/etc/localtime:ro
    #         - $HOME/.config/hamachi:/config
    #     restart: always
    #     environment:
    #         - ACCOUNT="myemail@gmail.com"
    #     privileged: true